// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// porque separar as structs ja geradas? pq vamos alterar no gqlgen de forma explicita
type NewCategory struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type NewCourse struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	CategoryID  string  `json:"categoryId"`
}
